# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(878, 736)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"add-to-cart-test.allthethings()-t-shirt-(red)\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".shopping_cart_badge").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"checkout\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"firstName\"]").send_keys("sumitra")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"lastName\"]").send_keys("pathak")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"postalCode\"]").send_keys("n22 3l2")
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"continue\"]").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"finish\"]").click()
  
